export const ADD_NAME = 'ADD_NAME';

export const ADD_LOG = 'ADD_LOG';

export const UPDATE_WIDGET = 'UPDATE_WIDGET';

export const CLEAR_LOGS = 'CLEAR_LOGS';

export const ADD_CHANNEL_KEY = 'ADD_CHANNEL_KEY';

export const SET_CHO_RATIO = 'SET_CHO_RATIO';

export const SET_INSULIN_SUGGESTIONS = 'SET_INSULIN_SUGGESTIONS';

export const UPDATE_MESSAGES_IN_CHANNEL = 'UPDATE_MESSAGES_IN_CHANNEL';

export const UPDATE_MESSAGES_SEEN = 'UPDATE_MESSAGES_SEEN';
