export const fakeJson = {
  common: [
    {
      food_name: 'burger',
      serving_unit: 'sandwich',
      tag_name: 'hamburger',
      serving_qty: 1,
      common_type: null,
      tag_id: '608',
      photo: {
        thumb: 'https://d2xdmhkmkbyw75.cloudfront.net/608_thumb.jpg',
      },
      locale: 'en_US',
    },
    {
      food_name: 'burgers',
      serving_unit: 'sandwich',
      tag_name: 'hamburger',
      serving_qty: 1,
      common_type: null,
      tag_id: '608',
      photo: {
        thumb: 'https://d2xdmhkmkbyw75.cloudfront.net/608_thumb.jpg',
      },
      locale: 'en_US',
    },
    {
      food_name: 'elk burger',
      serving_unit: 'burger on bun',
      tag_name: 'elk burger',
      serving_qty: 1,
      common_type: null,
      tag_id: '6873',
      photo: {
        thumb: 'https://d2eawub7utcl6.cloudfront.net/images/nix-apple-grey.png',
        highres: null,
        is_user_uploaded: false,
      },
      locale: 'en_US',
    },
    {
      food_name: 'burger bun',
      serving_unit: 'hamburger bun',
      tag_name: 'hamburger bun',
      serving_qty: 1,
      common_type: null,
      tag_id: '226',
      photo: {
        thumb: 'https://d2xdmhkmkbyw75.cloudfront.net/226_thumb.jpg',
      },
      locale: 'en_US',
    },
    {
      food_name: 'burger patty',
      serving_unit: 'oz',
      tag_name: 'hamburger patty',
      serving_qty: 3,
      common_type: null,
      tag_id: '2043',
      photo: {
        thumb: 'https://d2xdmhkmkbyw75.cloudfront.net/2043_thumb.jpg',
      },
      locale: 'en_US',
    },
    {
      food_name: 'vegan burger',
      serving_unit: 'burger',
      tag_name: 'vegan burger',
      serving_qty: 1,
      common_type: null,
      tag_id: '3532',
      photo: {
        thumb: 'https://d2xdmhkmkbyw75.cloudfront.net/3532_thumb.jpg',
      },
      locale: 'en_US',
    },
    {
      food_name: 'bison burger',
      serving_unit: 'burger on bun',
      tag_name: 'bison burger',
      serving_qty: 1,
      common_type: null,
      tag_id: '4048',
      photo: {
        thumb: 'https://d2eawub7utcl6.cloudfront.net/images/nix-apple-grey.png',
        highres: null,
        is_user_uploaded: false,
      },
      locale: 'en_US',
    },
    {
      food_name: 'bacon burger',
      serving_unit: 'item',
      tag_name: 'bacon cheeseburger',
      serving_qty: 1,
      common_type: null,
      tag_id: '1806',
      photo: {
        thumb: 'https://d2xdmhkmkbyw75.cloudfront.net/1806_thumb.jpg',
      },
      locale: 'en_US',
    },
    {
      food_name: 'veggie burger',
      serving_unit: 'veggie burger on bun',
      tag_name: 'veggie burger',
      serving_qty: 1,
      common_type: null,
      tag_id: '44',
      photo: {
        thumb: 'https://d2xdmhkmkbyw75.cloudfront.net/44_thumb.jpg',
      },
      locale: 'en_US',
    },
    {
      food_name: 'salmon burger',
      serving_unit: 'burger',
      tag_name: 'salmon burger',
      serving_qty: 1,
      common_type: null,
      tag_id: '1710',
      photo: {
        thumb: 'https://d2xdmhkmkbyw75.cloudfront.net/1710_thumb.jpg',
      },
      locale: 'en_US',
    },
    {
      food_name: 'turkey burger',
      serving_unit: 'burger on bun',
      tag_name: 'turkey burger',
      serving_qty: 1,
      common_type: null,
      tag_id: '1416',
      photo: {
        thumb: 'https://d2xdmhkmkbyw75.cloudfront.net/1416_thumb.jpg',
      },
      locale: 'en_US',
    },
    {
      food_name: 'chicken burger',
      serving_unit: 'burger on bun',
      tag_name: 'chicken burger',
      serving_qty: 1,
      common_type: null,
      tag_id: '1424',
      photo: {
        thumb: 'https://d2xdmhkmkbyw75.cloudfront.net/1424_thumb.jpg',
      },
      locale: 'en_US',
    },
    {
      food_name: 'chicken burgers',
      serving_unit: 'burger on bun',
      tag_name: 'chicken burger',
      serving_qty: 1,
      common_type: null,
      tag_id: '1424',
      photo: {
        thumb: 'https://d2xdmhkmkbyw75.cloudfront.net/1424_thumb.jpg',
      },
      locale: 'en_US',
    },
    {
      food_name: 'mcdonalds burger',
      serving_unit: 'sandwich',
      tag_name: 'mcdonalds hamburger',
      serving_qty: 1,
      common_type: null,
      tag_id: '2156',
      photo: {
        thumb: 'https://d2xdmhkmkbyw75.cloudfront.net/2156_thumb.jpg',
      },
      locale: 'en_US',
    },
    {
      food_name: 'blackbean burger',
      serving_unit: 'burger on bun',
      tag_name: 'black bean burger',
      serving_qty: 1,
      common_type: null,
      tag_id: '3650',
      photo: {
        thumb: 'https://d2xdmhkmkbyw75.cloudfront.net/3650_thumb.jpg',
      },
      locale: 'en_US',
    },
    {
      food_name: 'black bean burger',
      serving_unit: 'burger on bun',
      tag_name: 'black bean burger',
      serving_qty: 1,
      common_type: null,
      tag_id: '3650',
      photo: {
        thumb: 'https://d2xdmhkmkbyw75.cloudfront.net/3650_thumb.jpg',
      },
      locale: 'en_US',
    },
    {
      food_name: 'burger king whopper',
      serving_unit: 'item',
      tag_name: 'burger king whopper',
      serving_qty: 1,
      common_type: null,
      tag_id: '2058',
      photo: {
        thumb: 'https://d2xdmhkmkbyw75.cloudfront.net/2058_thumb.jpg',
      },
      locale: 'en_US',
    },
    {
      food_name: 'turkey burger patty',
      serving_unit: 'oz',
      tag_name: 'turkey burger patty',
      serving_qty: 3,
      common_type: null,
      tag_id: '5739',
      photo: {
        thumb: 'https://d2xdmhkmkbyw75.cloudfront.net/5739_thumb.jpg',
      },
      locale: 'en_US',
    },
    {
      food_name: 'burger king bacon whopper',
      serving_unit: 'g',
      tag_name: 'burger king bacon and cheese whopper',
      serving_qty: 289,
      common_type: 1,
      tag_id: '9813',
      photo: {
        thumb: 'https://d2eawub7utcl6.cloudfront.net/images/nix-apple-grey.png',
        highres: null,
        is_user_uploaded: false,
      },
      locale: 'en_US',
    },
    {
      food_name: 'burgerfi burgerfi cheeseburger',
      serving_unit: 'Serving',
      tag_name: 'burgerfi burgerfi cheeseburger',
      serving_qty: 1,
      common_type: 1,
      tag_id: '10545',
      photo: {
        thumb: 'https://d2eawub7utcl6.cloudfront.net/images/nix-apple-grey.png',
        highres: null,
        is_user_uploaded: false,
      },
      locale: 'en_US',
    },
  ],
  branded: [
    {
      food_name: 'Burgerfi Burger',
      serving_unit: 'serving',
      nix_brand_id: '513fbc1283aa2dc80c000316',
      brand_name_item_name: 'BurgerFi Burgerfi Burger',
      serving_qty: 1,
      nf_calories: 510,
      photo: {
        thumb: 'https://d2eawub7utcl6.cloudfront.net/images/nix-apple-grey.png',
        highres: null,
        is_user_uploaded: false,
      },
      brand_name: 'BurgerFi',
      region: 1,
      brand_type: 1,
      nix_item_id: '516d9a40e3afed032c7daae6',
      locale: 'en_US',
    },
    {
      food_name: 'Burgermaster',
      serving_unit: 'sandwich',
      nix_brand_id: '521b95474a56d006cae2a12c',
      brand_name_item_name: 'Burgermaster Burgermaster',
      serving_qty: 1,
      nf_calories: 790,
      photo: {
        thumb: 'https://d2eawub7utcl6.cloudfront.net/images/nix-apple-grey.png',
        highres: null,
        is_user_uploaded: false,
      },
      brand_name: 'Burgermaster',
      region: 1,
      brand_type: 1,
      nix_item_id: '53444fb59a631f1645ed046e',
      locale: 'en_US',
    },
    {
      food_name: 'Burgermelt',
      serving_unit: 'sandwich',
      nix_brand_id: '521b95474a56d006cae2a12c',
      brand_name_item_name: 'Burgermaster Burgermelt',
      serving_qty: 1,
      nf_calories: 1220,
      photo: {
        thumb: 'https://d2eawub7utcl6.cloudfront.net/images/nix-apple-grey.png',
        highres: null,
        is_user_uploaded: false,
      },
      brand_name: 'Burgermaster',
      region: 1,
      brand_type: 1,
      nix_item_id: '53444fb6cd5bb303a94c4cb1',
      locale: 'en_US',
    },
    {
      food_name: 'Burgerfi Cheeseburger',
      serving_unit: 'serving',
      nix_brand_id: '513fbc1283aa2dc80c000316',
      brand_name_item_name: 'BurgerFi Burgerfi Cheeseburger',
      serving_qty: 1,
      nf_calories: 650,
      photo: {
        thumb: 'https://d2eawub7utcl6.cloudfront.net/images/nix-apple-grey.png',
        highres: null,
        is_user_uploaded: false,
      },
      brand_name: 'BurgerFi',
      region: 1,
      brand_type: 1,
      nix_item_id: '516d9a40e3afed032c7daae7',
      locale: 'en_US',
    },
    {
      food_name: 'Burgerfi Chili',
      serving_unit: 'serving',
      nix_brand_id: '513fbc1283aa2dc80c000316',
      brand_name_item_name: 'BurgerFi Burgerfi Chili',
      serving_qty: 1,
      nf_calories: 80,
      photo: {
        thumb: 'https://d2eawub7utcl6.cloudfront.net/images/nix-apple-grey.png',
        highres: null,
        is_user_uploaded: false,
      },
      brand_name: 'BurgerFi',
      region: 1,
      brand_type: 1,
      nix_item_id: '516d9a40e3afed032c7daafd',
      locale: 'en_US',
    },
    {
      food_name: 'Conflicted Burger',
      serving_unit: 'serving',
      nix_brand_id: '513fbc1283aa2dc80c000316',
      brand_name_item_name: 'BurgerFi Conflicted Burger',
      serving_qty: 1,
      nf_calories: 700,
      photo: {
        thumb: 'https://d2eawub7utcl6.cloudfront.net/images/nix-apple-grey.png',
        highres: null,
        is_user_uploaded: false,
      },
      brand_name: 'BurgerFi',
      region: 1,
      brand_type: 1,
      nix_item_id: 'ddee1196150967c8e2244ae7',
      locale: 'en_US',
    },
    {
      food_name: 'Breakfast Burger',
      serving_unit: 'burger',
      nix_brand_id: '513fbc1283aa2dc80c00011b',
      brand_name_item_name: 'Burgerville Breakfast Burger',
      serving_qty: 1,
      nf_calories: 470,
      photo: {
        thumb: 'https://d2eawub7utcl6.cloudfront.net/images/nix-apple-grey.png',
        highres: null,
        is_user_uploaded: false,
      },
      brand_name: 'Burgerville',
      region: 1,
      brand_type: 1,
      nix_item_id: '23cb88169adae3a618d54cc4',
      locale: 'en_US',
    },
    {
      food_name: 'Burgerfi Sauce',
      serving_unit: 'serving',
      nix_brand_id: '513fbc1283aa2dc80c000316',
      brand_name_item_name: 'BurgerFi Burgerfi Sauce',
      serving_qty: 1,
      nf_calories: 40,
      photo: {
        thumb: 'https://d2eawub7utcl6.cloudfront.net/images/nix-apple-grey.png',
        highres: null,
        is_user_uploaded: false,
      },
      brand_name: 'BurgerFi',
      region: 1,
      brand_type: 1,
      nix_item_id: '516d9a40e3afed032c7daafe',
      locale: 'en_US',
    },
    {
      food_name: 'Tomato Burger',
      serving_unit: 'sandwich',
      nix_brand_id: '521b95474a56d006cae2a12c',
      brand_name_item_name: 'Burgermaster Tomato Burger',
      serving_qty: 1,
      nf_calories: 730,
      photo: {
        thumb: 'https://d2eawub7utcl6.cloudfront.net/images/nix-apple-grey.png',
        highres: null,
        is_user_uploaded: false,
      },
      brand_name: 'Burgermaster',
      region: 1,
      brand_type: 1,
      nix_item_id: '53444fb57ba4ca15456f606c',
      locale: 'en_US',
    },
    {
      food_name: 'Bacon Burger',
      serving_unit: 'sandwich',
      nix_brand_id: '521b95474a56d006cae2a12c',
      brand_name_item_name: 'Burgermaster Bacon Burger',
      serving_qty: 1,
      nf_calories: 960,
      photo: {
        thumb: 'https://d2eawub7utcl6.cloudfront.net/images/nix-apple-grey.png',
        highres: null,
        is_user_uploaded: false,
      },
      brand_name: 'Burgermaster',
      region: 1,
      brand_type: 1,
      nix_item_id: '53444fb6cd5bb303a94c4cac',
      locale: 'en_US',
    },
    {
      food_name: 'Vegefi Burger',
      serving_unit: 'serving',
      nix_brand_id: '513fbc1283aa2dc80c000316',
      brand_name_item_name: 'BurgerFi Vegefi Burger',
      serving_qty: 1,
      nf_calories: 520,
      photo: {
        thumb: 'https://d2eawub7utcl6.cloudfront.net/images/nix-apple-grey.png',
        highres: null,
        is_user_uploaded: false,
      },
      brand_name: 'BurgerFi',
      region: 1,
      brand_type: 1,
      nix_item_id: '516d9a40e3afed032c7daae9',
      locale: 'en_US',
    },
    {
      food_name: 'Smoke House Burger With Burger Patty Choice Gardein Burger',
      serving_unit: 'Serving',
      nix_brand_id: '513fbc1283aa2dc80c000044',
      brand_name_item_name:
        'Johnny Rockets Smoke House Burger With Burger Patty Choice Gardein Burger',
      serving_qty: 1,
      nf_calories: 530,
      photo: {
        thumb: 'https://d2eawub7utcl6.cloudfront.net/images/nix-apple-grey.png',
        highres: null,
        is_user_uploaded: false,
      },
      brand_name: 'Johnny Rockets',
      region: 1,
      brand_type: 1,
      nix_item_id: '15211603f1ea14c38d6a1342',
      locale: 'en_US',
    },
    {
      food_name: 'The Original Burger With Burger Patty Choice Turkey Burger',
      serving_unit: 'Serving',
      nix_brand_id: '513fbc1283aa2dc80c000044',
      brand_name_item_name:
        'Johnny Rockets The Original Burger With Burger Patty Choice Turkey Burger',
      serving_qty: 1,
      nf_calories: 580,
      photo: {
        thumb: 'https://d2eawub7utcl6.cloudfront.net/images/nix-apple-grey.png',
        highres: null,
        is_user_uploaded: false,
      },
      brand_name: 'Johnny Rockets',
      region: 1,
      brand_type: 1,
      nix_item_id: '1521160304496fb8c6d7dda7',
      locale: 'en_US',
    },
    {
      food_name: 'Bacon Cheddar Burger With Burger Patty Choice Gardein Burger',
      serving_unit: 'Serving',
      nix_brand_id: '513fbc1283aa2dc80c000044',
      brand_name_item_name:
        'Johnny Rockets Bacon Cheddar Burger With Burger Patty Choice Gardein Burger',
      serving_qty: 1,
      nf_calories: 500,
      photo: {
        thumb: 'https://d2eawub7utcl6.cloudfront.net/images/nix-apple-grey.png',
        highres: null,
        is_user_uploaded: false,
      },
      brand_name: 'Johnny Rockets',
      region: 1,
      brand_type: 1,
      nix_item_id: '152116034d3d0af97fb28c99',
      locale: 'en_US',
    },
    {
      food_name: 'Rocket Single Burger With Burger Patty Choice Beef Burger',
      serving_unit: 'Serving',
      nix_brand_id: '513fbc1283aa2dc80c000044',
      brand_name_item_name:
        'Johnny Rockets Rocket Single Burger With Burger Patty Choice Beef Burger',
      serving_qty: 1,
      nf_calories: 450,
      photo: {
        thumb: 'https://d2eawub7utcl6.cloudfront.net/images/nix-apple-grey.png',
        highres: null,
        is_user_uploaded: false,
      },
      brand_name: 'Johnny Rockets',
      region: 1,
      brand_type: 1,
      nix_item_id: '152116034ec2979d8424813e',
      locale: 'en_US',
    },
    {
      food_name: 'Rocket Single Burger With Burger Patty Choice Gardein Burger',
      serving_unit: 'Serving',
      nix_brand_id: '513fbc1283aa2dc80c000044',
      brand_name_item_name:
        'Johnny Rockets Rocket Single Burger With Burger Patty Choice Gardein Burger',
      serving_qty: 1,
      nf_calories: 410,
      photo: {
        thumb: 'https://d2eawub7utcl6.cloudfront.net/images/nix-apple-grey.png',
        highres: null,
        is_user_uploaded: false,
      },
      brand_name: 'Johnny Rockets',
      region: 1,
      brand_type: 1,
      nix_item_id: '15211603bb60edee6faff189',
      locale: 'en_US',
    },
    {
      food_name: 'Apollo Burger',
      serving_unit: 'Serving',
      nix_brand_id: '58c1de506fb63e4c1a779db1',
      brand_name_item_name: 'Apollo Burger Apollo Burger',
      serving_qty: 1,
      nf_calories: 840,
      photo: {
        thumb: 'https://d2eawub7utcl6.cloudfront.net/images/nix-apple-grey.png',
        highres: null,
        is_user_uploaded: false,
      },
      brand_name: 'Apollo Burger',
      region: 1,
      brand_type: 1,
      nix_item_id: 'c6405291e18b118f1263b884',
      locale: 'en_US',
    },
    {
      food_name: 'Athenian Burger',
      serving_unit: 'Serving',
      nix_brand_id: '58c1de506fb63e4c1a779db1',
      brand_name_item_name: 'Apollo Burger Athenian Burger',
      serving_qty: 1,
      nf_calories: 990,
      photo: {
        thumb: 'https://d2eawub7utcl6.cloudfront.net/images/nix-apple-grey.png',
        highres: null,
        is_user_uploaded: false,
      },
      brand_name: 'Apollo Burger',
      region: 1,
      brand_type: 1,
      nix_item_id: 'c6405291e13a4b37e211371b',
      locale: 'en_US',
    },
    {
      food_name: 'Cheeeesy Burger',
      serving_unit: 'burger',
      nix_brand_id: '59e8b940b3ea3f901643d3ae',
      brand_name_item_name: 'Wayback Burgers Cheeeesy Burger',
      serving_qty: 1,
      nf_calories: 830,
      photo: {
        thumb: 'https://d2eawub7utcl6.cloudfront.net/images/nix-apple-grey.png',
        highres: null,
        is_user_uploaded: false,
      },
      brand_name: 'Wayback Burgers',
      region: 1,
      brand_type: 1,
      nix_item_id: 'c640625488a088b6d6d6a87f',
      locale: 'en_US',
    },
    {
      food_name: 'Cheesy Burger',
      serving_unit: 'burger',
      nix_brand_id: '57f6b2314a6581d426d16e4a',
      brand_name_item_name: 'Burger 21 Cheesy Burger',
      serving_qty: 1,
      nf_calories: 550,
      photo: {
        thumb: 'https://d2eawub7utcl6.cloudfront.net/images/nix-apple-grey.png',
        highres: null,
        is_user_uploaded: false,
      },
      brand_name: 'Burger 21',
      region: 1,
      brand_type: 1,
      nix_item_id: 'c6404921f4e57e8bca32c39f',
      locale: 'en_US',
    },
  ],
};
